// Generated from: features/checkout-step-one.feature
import { test } from "playwright-bdd";

test.describe('Checkout Step One Tests @checkout-step-one', () => {

  test.beforeEach('Background', async ({ Given, When, page }, testInfo) => { if (testInfo.error) return;
    await Given('I am on the SauceDemo login page', null, { page }); 
    await When('I enter "standard_user" and "secret_sauce"', null, { page }); 
  });
  
  test('Verify that can complete the checkout step one pricess successfully', async ({ Given, When, Then, page }) => { 
    await Given('I added a product with name "Sauce Labs Backpack" to the cart', null, { page }); 
    await Then('I verify the number of items in the cart is 1', null, { page }); 
    await When('I click on the shopping cart link', null, { page }); 
    await When('I click on Checkout button', null, { page }); 
    await When('I enter the following fields:', {"dataTable":{"rows":[{"cells":[{"value":"field"},{"value":"value"}]},{"cells":[{"value":"firstName"},{"value":"John"}]},{"cells":[{"value":"lastName"},{"value":"Doe"}]},{"cells":[{"value":"postalCode"},{"value":"12345"}]}]}}, { page }); 
    await Then('I verify that redirected to the checkout step two page', null, { page }); 
  });

  test('Verify that a message "Error: First Name is required" when the first name field is empty', async ({ Given, When, Then, page }) => { 
    await Given('I added a product with name "Sauce Labs Backpack" to the cart', null, { page }); 
    await Then('I verify the number of items in the cart is 1', null, { page }); 
    await When('I click on the shopping cart link', null, { page }); 
    await When('I click on Checkout button', null, { page }); 
    await When('I enter the following fields:', {"dataTable":{"rows":[{"cells":[{"value":"field"},{"value":"value"}]},{"cells":[{"value":"firstName"},{"value":""}]},{"cells":[{"value":"lastName"},{"value":"Doe"}]},{"cells":[{"value":"postalCode"},{"value":"12345"}]}]}}, { page }); 
    await Then('I verify that a message "Error: First Name is required" is displayed', null, { page }); 
  });

  test('Verify that a message "Error: Last Name is required" when the last name field is empty', async ({ Given, When, Then, page }) => { 
    await Given('I added a product with name "Sauce Labs Backpack" to the cart', null, { page }); 
    await Then('I verify the number of items in the cart is 1', null, { page }); 
    await When('I click on the shopping cart link', null, { page }); 
    await When('I click on Checkout button', null, { page }); 
    await When('I enter the following fields:', {"dataTable":{"rows":[{"cells":[{"value":"field"},{"value":"value"}]},{"cells":[{"value":"firstName"},{"value":"John"}]},{"cells":[{"value":"lastName"},{"value":""}]},{"cells":[{"value":"postalCode"},{"value":"12345"}]}]}}, { page }); 
    await Then('I verify that a message "Error: Last Name is required" is displayed', null, { page }); 
  });

  test('Verify that a message "Error: Postal Code is required" when the postal code field is empty', async ({ Given, When, Then, page }) => { 
    await Given('I added a product with name "Sauce Labs Backpack" to the cart', null, { page }); 
    await Then('I verify the number of items in the cart is 1', null, { page }); 
    await When('I click on the shopping cart link', null, { page }); 
    await When('I click on Checkout button', null, { page }); 
    await When('I enter the following fields:', {"dataTable":{"rows":[{"cells":[{"value":"field"},{"value":"value"}]},{"cells":[{"value":"firstName"},{"value":"John"}]},{"cells":[{"value":"lastName"},{"value":"Doe"}]},{"cells":[{"value":"postalCode"},{"value":""}]}]}}, { page }); 
    await Then('I verify that a message "Error: Postal Code is required" is displayed', null, { page }); 
  });

  test('Verify that the product is still in the cart after clicking on cancel the checkout process', async ({ Given, When, Then, And, page }) => { 
    await Given('I have added the following products to the cart:', {"dataTable":{"rows":[{"cells":[{"value":"Sauce Labs Backpack"}]},{"cells":[{"value":"Sauce Labs Bike Light"}]}]}}, { page }); 
    await Then('I verify the number of items in the cart is 2', null, { page }); 
    await When('I click on the shopping cart link', null, { page }); 
    await When('I click on Checkout button', null, { page }); 
    await When('I click on Cancel button in checkout process', null, { page }); 
    await Then('I should be navigated back to the cart page', null, { page }); 
    await And('The cart should contain the following products:', {"dataTable":{"rows":[{"cells":[{"value":"Sauce Labs Backpack"}]},{"cells":[{"value":"Sauce Labs Bike Light"}]}]}}, { page }); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('features/checkout-step-one.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":11,"pickleLine":9,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given I am on the SauceDemo login page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When I enter \"standard_user\" and \"secret_sauce\"","isBg":true,"stepMatchArguments":[{"group":{"start":8,"value":"\"standard_user\"","children":[{"start":9,"value":"standard_user","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":28,"value":"\"secret_sauce\"","children":[{"start":29,"value":"secret_sauce","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":12,"gherkinStepLine":10,"keywordType":"Context","textWithKeyword":"Given I added a product with name \"Sauce Labs Backpack\" to the cart","stepMatchArguments":[{"group":{"start":28,"value":"\"Sauce Labs Backpack\"","children":[{"start":29,"value":"Sauce Labs Backpack","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":13,"gherkinStepLine":11,"keywordType":"Outcome","textWithKeyword":"Then I verify the number of items in the cart is 1","stepMatchArguments":[{"group":{"start":44,"value":"1"},"parameterTypeName":"int"}]},{"pwStepLine":14,"gherkinStepLine":12,"keywordType":"Action","textWithKeyword":"When I click on the shopping cart link","stepMatchArguments":[]},{"pwStepLine":15,"gherkinStepLine":13,"keywordType":"Action","textWithKeyword":"When I click on Checkout button","stepMatchArguments":[]},{"pwStepLine":16,"gherkinStepLine":14,"keywordType":"Action","textWithKeyword":"When I enter the following fields:","stepMatchArguments":[]},{"pwStepLine":17,"gherkinStepLine":19,"keywordType":"Outcome","textWithKeyword":"Then I verify that redirected to the checkout step two page","stepMatchArguments":[]}]},
  {"pwTestLine":20,"pickleLine":21,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given I am on the SauceDemo login page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When I enter \"standard_user\" and \"secret_sauce\"","isBg":true,"stepMatchArguments":[{"group":{"start":8,"value":"\"standard_user\"","children":[{"start":9,"value":"standard_user","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":28,"value":"\"secret_sauce\"","children":[{"start":29,"value":"secret_sauce","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":21,"gherkinStepLine":22,"keywordType":"Context","textWithKeyword":"Given I added a product with name \"Sauce Labs Backpack\" to the cart","stepMatchArguments":[{"group":{"start":28,"value":"\"Sauce Labs Backpack\"","children":[{"start":29,"value":"Sauce Labs Backpack","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":22,"gherkinStepLine":23,"keywordType":"Outcome","textWithKeyword":"Then I verify the number of items in the cart is 1","stepMatchArguments":[{"group":{"start":44,"value":"1"},"parameterTypeName":"int"}]},{"pwStepLine":23,"gherkinStepLine":24,"keywordType":"Action","textWithKeyword":"When I click on the shopping cart link","stepMatchArguments":[]},{"pwStepLine":24,"gherkinStepLine":25,"keywordType":"Action","textWithKeyword":"When I click on Checkout button","stepMatchArguments":[]},{"pwStepLine":25,"gherkinStepLine":26,"keywordType":"Action","textWithKeyword":"When I enter the following fields:","stepMatchArguments":[]},{"pwStepLine":26,"gherkinStepLine":31,"keywordType":"Outcome","textWithKeyword":"Then I verify that a message \"Error: First Name is required\" is displayed","stepMatchArguments":[{"group":{"start":24,"value":"\"Error: First Name is required\"","children":[{"start":25,"value":"Error: First Name is required","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":29,"pickleLine":33,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given I am on the SauceDemo login page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When I enter \"standard_user\" and \"secret_sauce\"","isBg":true,"stepMatchArguments":[{"group":{"start":8,"value":"\"standard_user\"","children":[{"start":9,"value":"standard_user","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":28,"value":"\"secret_sauce\"","children":[{"start":29,"value":"secret_sauce","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":30,"gherkinStepLine":34,"keywordType":"Context","textWithKeyword":"Given I added a product with name \"Sauce Labs Backpack\" to the cart","stepMatchArguments":[{"group":{"start":28,"value":"\"Sauce Labs Backpack\"","children":[{"start":29,"value":"Sauce Labs Backpack","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":31,"gherkinStepLine":35,"keywordType":"Outcome","textWithKeyword":"Then I verify the number of items in the cart is 1","stepMatchArguments":[{"group":{"start":44,"value":"1"},"parameterTypeName":"int"}]},{"pwStepLine":32,"gherkinStepLine":36,"keywordType":"Action","textWithKeyword":"When I click on the shopping cart link","stepMatchArguments":[]},{"pwStepLine":33,"gherkinStepLine":37,"keywordType":"Action","textWithKeyword":"When I click on Checkout button","stepMatchArguments":[]},{"pwStepLine":34,"gherkinStepLine":38,"keywordType":"Action","textWithKeyword":"When I enter the following fields:","stepMatchArguments":[]},{"pwStepLine":35,"gherkinStepLine":43,"keywordType":"Outcome","textWithKeyword":"Then I verify that a message \"Error: Last Name is required\" is displayed","stepMatchArguments":[{"group":{"start":24,"value":"\"Error: Last Name is required\"","children":[{"start":25,"value":"Error: Last Name is required","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":38,"pickleLine":45,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given I am on the SauceDemo login page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When I enter \"standard_user\" and \"secret_sauce\"","isBg":true,"stepMatchArguments":[{"group":{"start":8,"value":"\"standard_user\"","children":[{"start":9,"value":"standard_user","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":28,"value":"\"secret_sauce\"","children":[{"start":29,"value":"secret_sauce","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":39,"gherkinStepLine":46,"keywordType":"Context","textWithKeyword":"Given I added a product with name \"Sauce Labs Backpack\" to the cart","stepMatchArguments":[{"group":{"start":28,"value":"\"Sauce Labs Backpack\"","children":[{"start":29,"value":"Sauce Labs Backpack","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":40,"gherkinStepLine":47,"keywordType":"Outcome","textWithKeyword":"Then I verify the number of items in the cart is 1","stepMatchArguments":[{"group":{"start":44,"value":"1"},"parameterTypeName":"int"}]},{"pwStepLine":41,"gherkinStepLine":48,"keywordType":"Action","textWithKeyword":"When I click on the shopping cart link","stepMatchArguments":[]},{"pwStepLine":42,"gherkinStepLine":49,"keywordType":"Action","textWithKeyword":"When I click on Checkout button","stepMatchArguments":[]},{"pwStepLine":43,"gherkinStepLine":50,"keywordType":"Action","textWithKeyword":"When I enter the following fields:","stepMatchArguments":[]},{"pwStepLine":44,"gherkinStepLine":55,"keywordType":"Outcome","textWithKeyword":"Then I verify that a message \"Error: Postal Code is required\" is displayed","stepMatchArguments":[{"group":{"start":24,"value":"\"Error: Postal Code is required\"","children":[{"start":25,"value":"Error: Postal Code is required","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":47,"pickleLine":57,"tags":[],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given I am on the SauceDemo login page","isBg":true,"stepMatchArguments":[]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When I enter \"standard_user\" and \"secret_sauce\"","isBg":true,"stepMatchArguments":[{"group":{"start":8,"value":"\"standard_user\"","children":[{"start":9,"value":"standard_user","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"},{"group":{"start":28,"value":"\"secret_sauce\"","children":[{"start":29,"value":"secret_sauce","children":[{}]},{"children":[{}]}]},"parameterTypeName":"string"}]},{"pwStepLine":48,"gherkinStepLine":58,"keywordType":"Context","textWithKeyword":"Given I have added the following products to the cart:","stepMatchArguments":[]},{"pwStepLine":49,"gherkinStepLine":61,"keywordType":"Outcome","textWithKeyword":"Then I verify the number of items in the cart is 2","stepMatchArguments":[{"group":{"start":44,"value":"2"},"parameterTypeName":"int"}]},{"pwStepLine":50,"gherkinStepLine":62,"keywordType":"Action","textWithKeyword":"When I click on the shopping cart link","stepMatchArguments":[]},{"pwStepLine":51,"gherkinStepLine":63,"keywordType":"Action","textWithKeyword":"When I click on Checkout button","stepMatchArguments":[]},{"pwStepLine":52,"gherkinStepLine":64,"keywordType":"Action","textWithKeyword":"When I click on Cancel button in checkout process","stepMatchArguments":[]},{"pwStepLine":53,"gherkinStepLine":65,"keywordType":"Outcome","textWithKeyword":"Then I should be navigated back to the cart page","stepMatchArguments":[]},{"pwStepLine":54,"gherkinStepLine":66,"keywordType":"Outcome","textWithKeyword":"And The cart should contain the following products:","stepMatchArguments":[]}]},
]; // bdd-data-end